global class QuantityCheck{
      
      webservice static String checkAvaliability(String Quantity){
     /*    
        if(quantity!=null){           

           wwwApprouterComConnectorsWsdl.Provide_ServicePort req = new wwwApprouterComConnectorsWsdl.Provide_ServicePort();
           wwwApprouterComConnectorsResponse7.Product_element success = req.Provide_Service('F-110','3000','1038','DL','0000','00','0.000','0.000','0.0');
            
            if(repl_qty>Quantity){
                
                String result = repl_qty-Quantity;
                System.debug('Result:::'+result);
            }
            else{
                System.debug('Quantity is not available');
                
            }
        }
        else{        
              System.debug('Please enter the quantity');
        }
*/
        return quantity;
    }
  }